name: intl_translation
version: 0.20.0-wip
description: >-
  Contains code to deal with internationalized/localized messages,
  date and number formatting and parsing, bi-directional text, and
  other internationalization issues.
repository: https://github.com/dart-lang/i18n/tree/main/pkgs/intl_translation

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  analyzer: ^6.3.0
  args: ^2.5.0
  dart_style: ^2.3.6
  intl: ^0.19.0
  path: ^1.9.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.0.0
